version: '3.6'

services:
  db:
      image: mysql:8.0
      ports:
        - '32000:3306'
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ./dbinit:/docker-entrypoint-initdb.d/:ro